In [2]:
# Machine Learning 의 supervised learning 기법에 속하는 Recommendation 을 다룸 

In [24]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import missingno

In [4]:
# 1. 협력 필터링 (사람끼리 비교)
# Order Data (cont.) => 샀으면 1 안 샀으면 0 으로 만듦 => vectorization 
# Vector & Dimension (행으로 vector 만드는 방식, 열로 vector 만드는 방식)
# 사람 기반 -> 행으로 vector를 만듦 -> 각 행의 유사도 비교 
# 각 행 간의 내적을 통해 cosine similarity를 구해지는데 이를 통해 구한다.  
# 콘텐츠 기반 -> 열로 vector를 만듦

In [5]:
# 각 행 간의 내적을 통해 cosine similarity를 구하고 이를 통해 user similarity matrix를 만든다. 

In [6]:
# cosine 값이 크면 클 수록 매우 유사한 것이다. cosine 값을 구해서 user similarity matrix 에 넣는다. 

In [7]:
# 각 행에서 한 행의 번호가 1인데 이와 비교할 열들과 비교하여 가장 높은 값들부터 비교 
# 선택된 행의 번호 1에 속한 기존에 산 것들은 지움
# 최종 스코어 계산 

In [8]:
# 2. 콘텐츠 기반 필터링 (음반끼리 비교)
# Singer, Composer, Bitrate .. -> 열 기반으로 vector로 만들어서 feature로 만든다. (숫자화)
# Similarity Matrix 에 넣는다.
# K-Nearest Neighbor (knn) 사용 

In [10]:
# 대체재: 서로 대신 쓸 수 있는 관계에 있는 두 가지의 재화 (버터와 마가린, 쌀과 밀가루, 만년필과 연필)
# 보완재: 서로 보완관계에 있는 재화 
# 맥북을 카트에 담을 시 보완재로 노트북 가방과 파우치가 추천

In [1]:
#!pip install fastFM

In [5]:
%matplotlib inline

In [6]:
from sklearn.model_selection import learning_curve

In [7]:
from sklearn.feature_extraction import DictVectorizer # dictionary 형태를 Vectorize하는 것 

In [10]:
train = [
    {"user":"1","item":"5","age":19},
    {"user":"2","item":"43","age":33},
    {"user":"3","item":"20","age":55},
    {"user":"4","item":"10","age":20}
]
# key는 mutable한 것이 온다. 

In [9]:
v = DictVectorizer() # feature extraction <- 자연어 처리 

In [11]:
X = v.fit_transform(train) # fit_transform => feature scaling 포함  

In [13]:
X

<4x9 sparse matrix of type '<class 'numpy.float64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [14]:
dir(X)

['__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_binopt',
 '_boolean_index_to_array',
 '_check_boolean',
 '_check_ellipsis',
 '_cs_matrix__get_has_canonical_format',
 '_cs_matrix__get_sorted',
 '_cs_matrix_

In [20]:
dir(v) # inverse_transform을 쓰면 거꾸로 바꿔줌 

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_get_param_names',
 '_transform',
 'dtype',
 'feature_names_',
 'fit',
 'fit_transform',
 'get_feature_names',
 'get_params',
 'inverse_transform',
 'restrict',
 'separator',
 'set_params',
 'sort',
 'sparse',
 'transform',
 'vocabulary_']

In [21]:
# python 3.6 부터 뒤에서부터 바꾸어서 나오는 것으로 바뀌었다.
# 자연어 처리는 sparse matrix 구조로 되어있다. 
v.inverse_transform(X) 

[{'age': 19.0, 'item=5': 1.0, 'user=1': 1.0},
 {'age': 33.0, 'item=43': 1.0, 'user=2': 1.0},
 {'age': 55.0, 'item=20': 1.0, 'user=3': 1.0},
 {'age': 20.0, 'item=10': 1.0, 'user=4': 1.0}]

In [12]:
vars(X)

{'_shape': (4, 9),
 'maxprint': 50,
 'indices': array([0, 4, 5, 0, 3, 6, 0, 2, 7, 0, 1, 8], dtype=int32),
 'indptr': array([ 0,  3,  6,  9, 12], dtype=int32),
 'data': array([19.,  1.,  1., 33.,  1.,  1., 55.,  1.,  1., 20.,  1.,  1.]),
 '_has_sorted_indices': 1}

In [16]:
X.toarray() # sparce matrix 는 없는 값은 저장안함 

array([[19.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.],
       [33.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.],
       [55.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.],
       [20.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [18]:
print(X.toarray()) 
# one hot encoding (https://machinelearningmastery.com/how-to-one-hot-encode-sequence-data-in-python/)
# 총 9 개 -> 숫자 1개, 문자 4개, 문자 4개 

[[19.  0.  0.  0.  1.  1.  0.  0.  0.]
 [33.  0.  0.  1.  0.  0.  1.  0.  0.]
 [55.  0.  1.  0.  0.  0.  0.  1.  0.]
 [20.  1.  0.  0.  0.  0.  0.  0.  1.]]


In [22]:
# label encoding 은 크기 개념이 있어서 문제가 있다.
# one hot encoding 은 크기 개념이 없어서 좋다.
# 1 2 3 4
# 아래와 같이 변환 
# 1 0 0 0
# 0 1 0 0
# 0 0 1 0
# 0 0 0 1

In [27]:
# 영화 추천 데이터 
# 사용자 정보 읽어들이기 
u_cols = ['user_id','age','sex','occupation','zip_code']

In [28]:
users = pd.read_csv('ml-100k/u.user',sep='|',names=u_cols)

In [29]:
users

user_id  age sex     occupation zip_code
0          1   24   M     technician    85711
1          2   53   F          other    94043
2          3   23   M         writer    32067
3          4   24   M     technician    43537
4          5   33   F          other    15213
5          6   42   M      executive    98101
6          7   57   M  administrator    91344
7          8   36   M  administrator    05201
8          9   29   M        student    01002
9         10   53   M         lawyer    90703
10        11   39   F          other    30329
11        12   28   F          other    06405
12        13   47   M       educator    29206
13        14   45   M      scientist    55106
14        15   49   F       educator    97301
15        16   21   M  entertainment    10309
16        17   30   M     programmer    06355
17        18   35   F          other    37212
18        19   40   M      librarian    02138
19        20   42   F      homemaker    95660
20        21   26   M         writer    30068
21        22   25   M         writer    40206
22        23   30   F         artist    48197
23        24   21   F         artist    94533
24        25   39   M       engineer    55107
25        26   49   M       engineer    21044
26        27   40   F      librarian    30030
27        28   32   M         writer    55369
28        29   41   M     programmer    94043
29        30    7   M        student    55436
..       ...  ...  ..            ...      ...
913      914   44   F          other    08105
914      915   50   M  entertainment    60614
915      916   27   M       engineer    N2L5N
916      917   22   F        student    20006
917      918   40   M      scientist    70116
918      919   25   M          other    14216
919      920   30   F         artist    90008
920      921   20   F        student    98801
921      922   29   F  administrator    21114
922      923   21   M        student    E2E3R
923      924   29   M          other    11753
924      925   18   F       salesman    49036
925      926   49   M  entertainment    01701
926      927   23   M     programmer    55428
927      928   21   M        student    55408
928      929   44   M      scientist    53711
929      930   28   F      scientist    07310
930      931   60   M       educator    33556
931      932   58   M       educator    06437
932      933   28   M        student    48105
933      934   61   M       engineer    22902
934      935   42   M         doctor    66221
935      936   24   M          other    32789
936      937   48   M       educator    98072
937      938   38   F     technician    55038
938      939   26   F        student    33319
939      940   32   M  administrator    02215
940      941   20   M        student    97229
941      942   48   F      librarian    78209
942      943   22   M        student    77841

[943 rows x 5 columns]

In [30]:
# 영화 평점 데이터 
r_cols = ['user_id','movie_id','rating','unix_timestamp']

In [31]:
ratings = pd.read_csv('ml-100k/u.data',sep='\t',names=r_cols)

In [32]:
ratings['date'] = pd.to_datetime(ratings['unix_timestamp'],unit='s')

In [34]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
user_id           100000 non-null int64
movie_id          100000 non-null int64
rating            100000 non-null int64
unix_timestamp    100000 non-null int64
date              100000 non-null datetime64[ns]
dtypes: datetime64[ns](1), int64(4)
memory usage: 3.8 MB


In [33]:
ratings.head()

user_id  movie_id  rating  unix_timestamp                date
0      196       242       3       881250949 1997-12-04 15:55:49
1      186       302       3       891717742 1998-04-04 19:22:22
2       22       377       1       878887116 1997-11-07 07:18:36
3      244        51       2       880606923 1997-11-27 05:02:03
4      166       346       1       886397596 1998-02-02 05:33:16

In [36]:
# 영화 정보 불러들이기 
m_cols = ['movie_id','title','release_date','video_release_date','imdb_url']
movies = pd.read_csv('ml-100k/u.item',sep='|',names=m_cols,usecols=range(5),encoding='latin1')

In [37]:
movies

movie_id                                              title  \
0            1                                   Toy Story (1995)   
1            2                                   GoldenEye (1995)   
2            3                                  Four Rooms (1995)   
3            4                                  Get Shorty (1995)   
4            5                                     Copycat (1995)   
5            6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...   
6            7                              Twelve Monkeys (1995)   
7            8                                        Babe (1995)   
8            9                            Dead Man Walking (1995)   
9           10                                 Richard III (1995)   
10          11                               Seven (Se7en) (1995)   
11          12                         Usual Suspects, The (1995)   
12          13                            Mighty Aphrodite (1995)   
13          14                                 Postino, Il (1994)   
14          15                          Mr. Holland's Opus (1995)   
15          16                 French Twist (Gazon maudit) (1995)   
16          17                         From Dusk Till Dawn (1996)   
17          18                          White Balloon, The (1995)   
18          19                              Antonia's Line (1995)   
19          20                          Angels and Insects (1995)   
20          21                      Muppet Treasure Island (1996)   
21          22                                  Braveheart (1995)   
22          23                                 Taxi Driver (1976)   
23          24                         Rumble in the Bronx (1995)   
24          25                               Birdcage, The (1996)   
25          26                      Brothers McMullen, The (1995)   
26          27                                    Bad Boys (1995)   
27          28                                   Apollo 13 (1995)   
28          29                              Batman Forever (1995)   
29          30                               Belle de jour (1967)   
...        ...                                                ...   
1652      1653  Entertaining Angels: The Dorothy Day Story (1996)   
1653      1654                       Chairman of the Board (1998)   
1654      1655                                  Favor, The (1994)   
1655      1656                                 Little City (1998)   
1656      1657                                      Target (1995)   
1657      1658                      Substance of Fire, The (1996)   
1658      1659                    Getting Away With Murder (1996)   
1659      1660                                 Small Faces (1995)   
1660      1661                                New Age, The (1994)   
1661      1662                                 Rough Magic (1995)   
1662      1663                            Nothing Personal (1995)   
1663      1664                     8 Heads in a Duffel Bag (1997)   
1664      1665                           Brother's Kiss, A (1997)   
1665      1666                                        Ripe (1996)   
1666      1667                              Next Step, The (1995)   
1667      1668                          Wedding Bell Blues (1996)   
1668      1669                           MURDER and murder (1996)   
1669      1670                                     Tainted (1998)   
1670      1671                          Further Gesture, A (1996)   
1671      1672                                        Kika (1993)   
1672      1673                                      Mirage (1995)   
1673      1674                                  Mamma Roma (1962)   
1674      1675                              Sunchaser, The (1996)   
1675      1676                            War at Home, The (1996)   
1676      1677                               Sweet Nothing (1995)   
1677      1678                                  Mat' i syn (1997)   
1678

In [38]:
# 사용자 + 영화 평점 + 영화 세 가지 정보 합치기 
movie_rating = pd.merge(movies, ratings)

In [39]:
lens = pd.merge(movie_rating,users)

In [40]:
lens.head()

movie_id                  title release_date  video_release_date  \
0         1       Toy Story (1995)  01-Jan-1995                 NaN   
1         4      Get Shorty (1995)  01-Jan-1995                 NaN   
2         5         Copycat (1995)  01-Jan-1995                 NaN   
3         7  Twelve Monkeys (1995)  01-Jan-1995                 NaN   
4         8            Babe (1995)  01-Jan-1995                 NaN   

                                            imdb_url  user_id  rating  \
0  http://us.imdb.com/M/title-exact?Toy%20Story%2...      308       4   
1  http://us.imdb.com/M/title-exact?Get%20Shorty%...      308       5   
2  http://us.imdb.com/M/title-exact?Copycat%20(1995)      308       4   
3  http://us.imdb.com/M/title-exact?Twelve%20Monk...      308       4   
4     http://us.imdb.com/M/title-exact?Babe%20(1995)      308       5   

   unix_timestamp                date  age sex occupation zip_code  
0       887736532 1998-02-17 17:28:52   60   M    retired    95076  
1       887737890 1998-02-17 17:51:30   60   M    retired    95076  
2       887739608 1998-02-17 18:20:08   60   M    retired    95076  
3       887738847 1998-02-17 18:07:27   60   M    retired    95076  
4       887736696 1998-02-17 17:31:36   60   M    retired    95076

In [41]:
lens.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 99999
Data columns (total 13 columns):
movie_id              100000 non-null int64
title                 100000 non-null object
release_date          99991 non-null object
video_release_date    0 non-null float64
imdb_url              99987 non-null object
user_id               100000 non-null int64
rating                100000 non-null int64
unix_timestamp        100000 non-null int64
date                  100000 non-null datetime64[ns]
age                   100000 non-null int64
sex                   100000 non-null object
occupation            100000 non-null object
zip_code              100000 non-null object
dtypes: datetime64[ns](1), float64(1), int64(5), object(6)
memory usage: 10.7+ MB


In [43]:
lens.describe() # movie_id, rating 

movie_id  video_release_date       user_id         rating  \
count  100000.000000                 0.0  100000.00000  100000.000000   
mean      425.530130                 NaN     462.48475       3.529860   
std       330.798356                 NaN     266.61442       1.125674   
min         1.000000                 NaN       1.00000       1.000000   
25%       175.000000                 NaN     254.00000       3.000000   
50%       322.000000                 NaN     447.00000       4.000000   
75%       631.000000                 NaN     682.00000       4.000000   
max      1682.000000                 NaN     943.00000       5.000000   

       unix_timestamp            age  
count    1.000000e+05  100000.000000  
mean     8.835289e+08      32.969850  
std      5.343856e+06      11.562623  
min      8.747247e+08       7.000000  
25%      8.794487e+08      24.000000  
50%      8.828269e+08      30.000000  
75%      8.882600e+08      40.000000  
max      8.932866e+08      73.000000

In [45]:
lens.sort_values('rating',ascending=False)

movie_id                                            title release_date  \
48743        25                             Birdcage, The (1996)  08-Mar-1996   
46595       705                       Singin' in the Rain (1952)  01-Jan-1952   
20919      1286                           Shall We Dance? (1937)  01-Jan-1937   
46621       780                             Dumb & Dumber (1994)  01-Jan-1994   
20917      1262                       Walking and Talking (1996)  12-Jul-1996   
20914      1221                  When a Man Loves a Woman (1994)  01-Jan-1994   
46625       792                     Bullets Over Broadway (1994)  01-Jan-1994   
20911      1189                               Prefontaine (1997)  24-Jan-1997   
91551        48                               Hoop Dreams (1994)  01-Jan-1994   
86864      1524                             Kaspar Hauser (1993)  07-Jun-1996   
20900      1119                    Some Kind of Wonderful (1987)  01-Jan-1987   
91548        23                               Taxi Driver (1976)  16-Feb-1996   
76952       251                           Shall We Dance? (1996)  11-Jul-1997   
95815       173                       Princess Bride, The (1987)  01-Jan-1987   
20894      1074                             Reality Bites (1994)  01-Jan-1994   
20893      1058                                  War, The (1994)  01-Jan-1994   
91546        14                               Postino, Il (1994)  01-Jan-1994   
76958       285                            Secrets & Lies (1996)  04-Oct-1996   
76959       286                      English Patient, The (1996)  15-Nov-1996   
20885      1020                                  Gaslight (1944)  01-Jan-1944   
20884      1016                                   Con Air (1997)  06-Jun-1997   
86866         8                                      Babe (1995)  01-Jan-1995   
20880      1007                       Waiting for Guffman (1996)  31-Jan-1997   
91541       328                         Conspiracy Theory (1997)  08-Aug-1997   
67953       572                                Blown Away (1994)  01-Jan-1994   
76942       208                        Young Frankenstein (1974)  01-Jan-1974   
85334       421    William Shakespeare's Romeo and Juliet (1996)  25-Oct-1996   
85335       427                     To Kill a Mockingbird (1962)  01-Jan-1962   
20946        12                       Usual Suspects, The (1995)  14-Aug-1995   
20961        50                                 Star Wars (1977)  01-Jan-1977   
...         ...                                              ...          ...   
46922       976                                      Solo (1996)  23-Aug-1996   
46823       738                                 Threesome (1994)  01-Jan-1994   
46831       785                                  Only You (1994)  01-Jan-1994   
46835       845                        That Thing You Do! (1996)  28-Sep-1996   
46837       864                       My Fellow Americans (1996)  20-Dec-1996   
46839       926                            Down Periscope (1996)  01-Mar-1996   
46842       998                                 Cabin Boy (1994)  01-Jan-1994   
46847      1037                                  Grease 2 (1982)  01-Jan-1982   
46852      1054                                 Mr. Wrong (1996)  16-Feb-1996   
46856      1079                           Joe's Apartment (1996)  26-Jul-1996   
46857      1094        Thin Line Between Love and Hate, A (1996)  03-Apr-1996   
46860      1183                           Cowboy Way, The (1994)  01-Jan-1994   
46866      1446                             Bye Bye, Love (1995)  01-Jan-1995   
46867      1496                                   Carpool (1996)  23-Aug-1996   
46937       252            Lost World: Jurassic Park, The (1997)  23-May-1997   
47304       431                                Highlander (1986)  01-Jan-1986   
46938       254                            Batman & Robin (1997)  20-Jun-1997   
46991       476                     Fi

In [46]:

lens.title.value_counts()

Star Wars (1977)                                      583
Contact (1997)                                        509
Fargo (1996)                                          508
Return of the Jedi (1983)                             507
Liar Liar (1997)                                      485
English Patient, The (1996)                           481
Scream (1996)                                         478
Toy Story (1995)                                      452
Air Force One (1997)                                  431
Independence Day (ID4) (1996)                         429
Raiders of the Lost Ark (1981)                        420
Godfather, The (1972)                                 413
Pulp Fiction (1994)                                   394
Twelve Monkeys (1995)                                 392
Silence of the Lambs, The (1991)                      390
Jerry Maguire (1996)                                  384
Chasing Amy (1997)                                    379
Rock, The (199

In [47]:
# 가장 평점 많이 받은 25개 작품 
lens.title.value_counts()[:25]

Star Wars (1977)                             583
Contact (1997)                               509
Fargo (1996)                                 508
Return of the Jedi (1983)                    507
Liar Liar (1997)                             485
English Patient, The (1996)                  481
Scream (1996)                                478
Toy Story (1995)                             452
Air Force One (1997)                         431
Independence Day (ID4) (1996)                429
Raiders of the Lost Ark (1981)               420
Godfather, The (1972)                        413
Pulp Fiction (1994)                          394
Twelve Monkeys (1995)                        392
Silence of the Lambs, The (1991)             390
Jerry Maguire (1996)                         384
Chasing Amy (1997)                           379
Rock, The (1996)                             378
Empire Strikes Back, The (1980)              367
Star Trek: First Contact (1996)              365
Back to the Future (

In [49]:
# 사용자별 평가 횟수와 평점 평균 -> EDA 
user_stats = lens.groupby('user_id').agg({'rating': [np.size, np.mean]})
user_stats['rating'].describe()

size        mean
count  943.000000  943.000000
mean   106.044539    3.588191
std    100.931743    0.445233
min     20.000000    1.491954
25%     33.000000    3.323054
50%     65.000000    3.620690
75%    148.000000    3.869565
max    737.000000    4.869565

In [51]:
# EDA 후 vectorize (문자를 숫자로 바꾸기)
# vectorize 후 train_test_split 

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
# 3가지 -> fast FM, fast AI 
# one hot encoding 예측 <- Scikit 으로 예측가능 
# 영화 제목 예측이 목표 

In [54]:
# X에 개인정보가 들어갔을 때 Y에 영화 제목 나옴 