In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import missingno
# fetch로 시작하는 라이브러리 -> 대용량 
# make으로 시작하는 라이브러리 -> 로직 증명
# load로 시작하는 라이브버리 -> 작은 데이터 load_iris (전부 소문자) => 함수 
from sklearn.datasets import load_iris 
from sklearn.neighbors import KNeighborsClassifier # 지도학습 -> 분류 classification 선택 
np.random.seed(1) # 순서를 정해놓는다. 
np.random.randint(10) # 재연가능성을 정해놓는다. kernel 다시 껐다 켜도 똑같이 나온다. 
from sklearn.model_selection import train_test_split # 학습시킬 것과 테스트할 것을 분리시킴 
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression # logistic regression 기법 
from sklearn.model_selection import KFold # K-Fold Cross Validation shuffle: 중복포함 
from sklearn.model_selection import cross_val_score 
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KDTree
plt.rcParams['font.family'] = 'KoPubWorldBatang_Pro'

In [127]:
data = pd.read_csv('iris.data',header=None)

In [128]:
data

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
5    5.4  3.9  1.7  0.4     Iris-setosa
6    4.6  3.4  1.4  0.3     Iris-setosa
7    5.0  3.4  1.5  0.2     Iris-setosa
8    4.4  2.9  1.4  0.2     Iris-setosa
9    4.9  3.1  1.5  0.1     Iris-setosa
10   5.4  3.7  1.5  0.2     Iris-setosa
11   4.8  3.4  1.6  0.2     Iris-setosa
12   4.8  3.0  1.4  0.1     Iris-setosa
13   4.3  3.0  1.1  0.1     Iris-setosa
14   5.8  4.0  1.2  0.2     Iris-setosa
15   5.7  4.4  1.5  0.4     Iris-setosa
16   5.4  3.9  1.3  0.4     Iris-setosa
17   5.1  3.5  1.4  0.3     Iris-setosa
18   5.7  3.8  1.7  0.3     Iris-setosa
19   5.1  3.8  1.5  0.3     Iris-setosa
20   5.4  3.4  1.7  0.2     Iris-setosa
21   5.1  3.7  1.5  0.4     Iris-setosa
22   4.6  3.6  1.0  0.2     Iris-setosa
23   5.1  3.3  1.7  0.5     Iris-setosa
24   4.8  3.4  1.9  0.2     Iris-setosa
25   5.0  3.0  1.6  0.2     Iris-setosa
26   5.0  3.4  1.6  0.4     Iris-setosa
27   5.2  3.5  1.5  0.2     Iris-setosa
28   5.2  3.4  1.4  0.2     Iris-setosa
29   4.7  3.2  1.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
120  6.9  3.2  5.7  2.3  Iris-virginica
121  5.6  2.8  4.9  2.0  Iris-virginica
122  7.7  2.8  6.7  2.0  Iris-virginica
123  6.3  2.7  4.9  1.8  Iris-virginica
124  6.7  3.3  5.7  2.1  Iris-virginica
125  7.2  3.2  6.0  1.8  Iris-virginica
126  6.2  2.8  4.8  1.8  Iris-virginica
127  6.1  3.0  4.9  1.8  Iris-virginica
128  6.4  2.8  5.6  2.1  Iris-virginica
129  7.2  3.0  5.8  1.6  Iris-virginica
130  7.4  2.8  6.1  1.9  Iris-virginica
131  7.9  3.8  6.4  2.0  Iris-virginica
132  6.4  2.8  5.6  2.2  Iris-virginica
133  6.3  2.8  5.1  1.5  Iris-virginica
134  6.1  2.6  5.6  1.4  Iris-virginica
135  7.7  3.0  6.1  2.3  Iris-virginica
136  6.3  3.4  5.6  2.4  Iris-virginica
137  6.4  3.1  5.5  1.8  Iris-virginica
138  6.0  3.0  4.8  1.8  Iris-virginica
139  6.9  3.1  5.4  2.1  Iris-virginica
140  6.7  3.1  5.6  2.4  Iris-virginica
141  6.9  3.1  5.1  2.3  Iris-virginica
142  5.8  2.7  5.1  1.9  Iris-virginica
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
0    150 non-null float64
1    150 non-null float64
2    150 non-null float64
3    150 non-null float64
4    150 non-null object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB


In [17]:
data.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [64]:
X_train, X_test, y_train, y_test = train_test_split(data[data.columns[:-1]],data.iloc[:,-1])

In [47]:
knn = KNeighborsClassifier()

In [48]:
knn.fit(X_train,y_train) # model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [43]:
knn.score(X_test,y_test) # random 하게 나누기 때문에 컴퓨터마다 다르고 매번 실행할 때마다 다르다. -> overfitting 90% 
# 간단하게 얼마나 맞추는 건지 테스트하는 함수가 score

0.9473684210526315

In [44]:
# infer하는 방식 2가지  
# train test split -> hold out 방식 <- 데이터가 많을 때만 사용 가능 => 현재 상태는 데이터가 적어서 어려움 
# cross validation 

In [49]:
knn.predict_proba([[3,2,3,3]]) # 확률 계산 => 가장 큰 확률로 예측 

array([[0. , 0.8, 0.2]])

In [50]:
# 모든 알고리즘을 확률로 계산할 수 없다. 
# determistic algorithm vs probability algorithm => 확률 기반 알고리즘이 더 우아하다.
# knn은 확률 기반 알고리즘이 아니다. 

In [55]:
# logistic regression => 이름은 regression으로 끝나지만 classification 기법이다. 
# from sklearn.linear_model import LogisticRegression

In [57]:
log_reg = LogisticRegression()

In [58]:
log_reg.fit(X_train,y_train)

/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [59]:
log_reg.score(X_test,y_test)

0.8421052631578947

In [60]:
# knn vs logistic regression
# knn -> 점을 기준으로 거리가 가까운 점들이 모여있으면 그걸 선택하는 것 
# logistic regression -> linear regression을 보완한 방법으로 클러스터끼리 곡선으로 연결
# 위 두개의 방법을 보완하기 위해 Cross Validation (CV) 기법을 쓴다. 
# K-fold CV -> K가 10이면 데이터를 10등분하고 (150 / 10 -> 15) 각 등분한 것에 대해 train_data, test_data로 나누고 
# 총 10개의 모델이 나오는데 각 모델에 대해서 score를 하고 평균을 산출한 것이 K-fold CV 이다. 
# 이로 인해 모든 데이터를 학습시키기 때문에 장점이 있다.
# hold out은 1번만 하고 결과 예측이 가능한 반면 보통 CV는 보통 10등분해서 계산하기 때문에 시간이 많이 걸리고 최종 결과를 예측할 수 없다.

In [96]:
kFold = KFold(10)

In [97]:
x = kFold.split(data[data.columns[:-1]],data.iloc[:,-1]) # next()

In [98]:
temp = []
for i,j in x:
    knn = KNeighborsClassifier()
    knn.fit(data.iloc[i,:-1],data.iloc[i,-1])
    temp.append(knn.score(data.iloc[j,:-1],data.iloc[j,-1]))

In [99]:
temp

[1.0,
 1.0,
 1.0,
 1.0,
 0.8,
 0.8666666666666667,
 1.0,
 0.8666666666666667,
 0.8,
 1.0]

In [100]:
np.mean(temp)

0.9333333333333333

In [104]:
# data 의 양이 작으면 K-fold cross validation 방식 
# K가 5면 5번 training -> 최종 모델이 아니기 때문에 대충의 성능을 확인하는 용도로 쓰고 overfitting 막기 위해 
# K-fold cross validation 을 쓴다. 
# scikit에서는 K-fold cross validation을 hyper parameter를 찾기 위한 용도로 쓰인다. 
# K가 10이면 1개의 test data와 9개의 train data로 나누어진다. 
# data 의 양이 크면 hold out 방식 

In [108]:
knn = KNeighborsClassifier()
t = cross_val_score(knn,data[data.columns[:-1]],data.iloc[:,-1],cv=10)  # estimator -> 모델 (인스턴스)

In [109]:
np.mean(t)

0.9666666666666668

In [110]:
log_reg = LogisticRegression()
h = cross_val_score(log_reg,data[data.columns[:-1]],data.iloc[:,-1],cv=10)

/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/si

In [111]:
h

array([1.        , 1.        , 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.8       , 0.93333333, 1.        , 1.        ])

In [112]:
np.mean(h)

0.9533333333333334

In [113]:
knn = KNeighborsClassifier()
t = cross_val_score(knn,data.iloc[:,:-1],data.iloc[:,-1],cv=10)

In [114]:
t

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [115]:
np.mean(t)

0.9666666666666668

In [119]:
log_reg = LogisticRegression()
h = cross_val_score(log_reg,data.iloc[:,:-1],data.iloc[:,-1],cv=10)

/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/si

In [120]:
h

array([1.        , 1.        , 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.8       , 0.93333333, 1.        , 1.        ])

In [121]:
np.mean(h)

0.9533333333333334

In [122]:
gauNB = GaussianNB()
g = cross_val_score(gauNB,data.iloc[:,:-1],data.iloc[:,-1],cv=10) # 대충의 성능 확인 

In [123]:
g

array([0.93333333, 0.93333333, 1.        , 0.93333333, 0.93333333,
       0.93333333, 0.86666667, 1.        , 1.        , 1.        ])

In [124]:
np.mean(g)

0.9533333333333334

In [125]:
# knn = KNeighborsClassifier() 클래스 생성시 들어가는 파라메터가 hyper parameter인데 이에 따라 모델이 달라짐 

In [129]:
# KNN => 인스턴스 베이스 러닝 또는 케이스 러닝 또는 레이지 러닝이라고 한다. 
# KNN은 유사도 기반으로 예측 (찾고자 하는 것과 주위의 것들의 거리가 가까운 순으로 찾음)
# 유클리디언 디스턴스 
# n_neighbor=5, weights='uniform', algorithm='auto'
# metric='minkowski', metric_params=None

In [130]:
knn3 = KNeighborsClassifier(3)
knn5 = KNeighborsClassifier(5)
knn7 = KNeighborsClassifier(7)

In [131]:
knn3_r = cross_val_score(knn3,data.iloc[:,:-1],data.iloc[:,-1],cv=10)
knn5_r = cross_val_score(knn5,data.iloc[:,:-1],data.iloc[:,-1],cv=10)
knn7_r = cross_val_score(knn7,data.iloc[:,:-1],data.iloc[:,-1],cv=10)

In [132]:
np.mean(knn3_r)

0.9666666666666666

In [133]:
np.mean(knn5_r)

0.9666666666666668

In [134]:
np.mean(knn7_r)

0.9666666666666668

In [135]:
# 위의 결과로 인해 파라메터 바꾸는 것보다 알고리즘 바꾸는 게 더 좋다는 것을 알 수 있다. 

In [138]:
log_reg1 = LogisticRegression(C=1.0) # n_jobs -> -1 전체 코어 / 1 -> 1개의 코어

In [139]:
log_reg2 = LogisticRegression(C=2.0)

In [140]:
log_reg3 = LogisticRegression(C=3.0)

In [141]:
log_reg1_r = cross_val_score(log_reg1,data.iloc[:,:-1],data.iloc[:,-1],cv=10)
log_reg2_r = cross_val_score(log_reg2,data.iloc[:,:-1],data.iloc[:,-1],cv=10)
log_reg3_r = cross_val_score(log_reg3,data.iloc[:,:-1],data.iloc[:,-1],cv=10)

/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
/Users/jung-kyoyoon/anaconda3/lib/python3.7/si

In [142]:
np.mean(log_reg1_r)

0.9533333333333334

In [143]:
np.mean(log_reg2_r)

0.9600000000000002

In [144]:
np.mean(log_reg3_r)

0.9600000000000002

In [145]:
# 자동적으로 파라메터 찾아주기 구현하는 것 내일 할 예정 

In [146]:
# 알고리즘, 하이퍼 파라메터에 따라 모델의 성능이 바뀔 수 있다. 
# 실질적으로 성능이 많이 바뀌는 것은 데이터의 값을 바꾸는 것에 기인한다.