In [1]:
# 파이선 단점
# 속도가 느리다 / 모바일 지원이 안 된다. 

In [7]:
# 속도가 느리다는 것을 보완하는 방법
# 하드웨어 기반 분산시스템 (여러 개의 CPU)
# 하드웨어 기반 GPU 사용
# Glue Language 특성을 활용하여 병목현상이 일어나는 곳을 C code 로 구성
# 자료구조 및 알고리즘 최적화 (efficient algorithm -> vectorization)

In [8]:
# Numpy -> 효율적인 자료구조(ndarray) / Glue Language 특성을 통한 최적화 (C code 로 구성) => 속도를 빠르게 하여 빅데이터 처리

In [9]:
# Numpy 를 쓰면 좋은 점 및 단점
# for/while loop 없이 데이터 탐색을 가능하게 하는 기술 -> Vectorization (CPU 연산 최적화, 동시에 많은 데이터 처리)
# GPU를 지원하지 않고 데이터가 너무 작으면 의미가 없다 

In [77]:
# Numpy를 쓰기 위해 ndarray 생성 방법
# 새로 생성 -> Numpy 형태로 변환 
# 복사 (copy(원본 유지, 복사본만 변경), view (원본과 복사본 동시 변경))
# 파일 불러오는 것 
# 랜덤으로 불러오는 것 

In [37]:
import numpy as np 

In [38]:
a = [[1.,0.,0.],[0.,1.,2.]]

In [39]:
b = np.array(a)

In [40]:
b.shape

(2, 3)

In [41]:
b.dtype

dtype('float64')

In [42]:
b.size

6

In [43]:
b.itemsize # float64 => 64 / 8 = 8

8

In [44]:
b.ndim # 차원 

2

In [45]:
b.strides # 24 / 8, 8(itemsize) / 8 => 3,1 

(24, 8)

In [35]:
b.flags # C_CONTIGUOUS 가 true 이므로 C 형태이다. 

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [46]:
b.argmax

<function ndarray.argmax>

In [48]:
# universal function => vectorization 화된 function => argmax()
b.argmax() # 원소 중 가장 큰 값 0,1,2,3,4,5 

5

In [51]:
a = np.arange(15).reshape(3,-1) # -1 인 것은 3을 기준으로 알아서 생성해라. (3,5) 와 동일함 

In [52]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
a = np.arange(15).reshape(-1,5)

In [55]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
c = np.array([1,2,3],dtype=np.int8) # np.int_ 와 같이 끝에 _ 가 붙으면 파이선에서 지원하는 방식 / '?' => literal 방식  

In [63]:
c

array([1, 2, 3], dtype=int8)

In [72]:
a = b'abc' # byte 변환 

In [73]:
c = np.array(a)

In [75]:
c # '|S3' / '<U3' little-endian 

array(b'abc', dtype='|S3')

In [76]:
print(c)

b'abc'
