In [1]:
import numpy as np 

In [3]:
a = np.arange(10).reshape(2,5)
b = np.arange(10,20).reshape(2,5)

In [4]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
b

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [7]:
a.dot(b.T)

array([[130, 180],
       [430, 605]])

In [8]:
np.dot(a,b.T)

array([[130, 180],
       [430, 605]])

In [10]:
np.vstack((a,b))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
np.hstack((a,b))

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [15]:
np.r_[a,b] # copy 원본보다 더 커지면 copy 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [16]:
np.c_[a,b] # copy

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [17]:
x = np.r_[a,b]

In [18]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [19]:
np.vsplit(x,(1,3)) # x.vsplit 지원안됨 

[array([[0, 1, 2, 3, 4]]), array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19]])]

In [20]:
np.vsplit(x,2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]), array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [25]:
np.vsplit(x,[2,2])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([], shape=(0, 5), dtype=int64),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [26]:
x = np.arange(10).reshape(0,5)

ValueError: cannot reshape array of size 10 into shape (0,5)

In [22]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
np.vsplit(x,[1,1])

[array([[0, 1, 2, 3, 4]]),
 array([], shape=(0, 5), dtype=int64),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [24]:
np.vsplit(x,[3,6])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]]),
 array([], shape=(0, 5), dtype=int64)]

In [27]:
# Linear Algebra

In [40]:
a = np.array([[2,3],[1,2]]) # matrix A * matrix X ([a,b],[c,d]) = matrix B ([1,2],[3,4]) => X는 무엇인가? 

In [29]:
np.invert(a)

array([[-3, -4],
       [-2, -3]])

In [30]:
b = np.mat(a)

In [31]:
b

matrix([[2, 3],
        [1, 2]])

In [38]:
b.I # 역행렬 

matrix([[ 2., -3.],
        [-1.,  2.]])

In [39]:
b.I@np.array([[1,2],[3,4]])

matrix([[-7., -8.],
        [ 5.,  6.]])