In [5]:
import numpy as np 

In [6]:
a = b'abc' # byte 변환

In [7]:
c = np.array(a)

In [8]:
c # '|S3' / '<U3' little-endian 

array(b'abc', dtype='|S3')

In [9]:
c.__repr__

<method-wrapper '__repr__' of numpy.ndarray object at 0x10530a2b0>

In [10]:
c.__str__()

"b'abc'"

In [11]:
print(c)

b'abc'


In [14]:
d = np.array( [ [1,2], [3,4] ], dtype=np.complex ) # 복소수 

In [15]:
d

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [16]:
# print 를 실행하면 __str__ 에 있는 내용을 보여주고 그냥 실행하면 __repr__ 을 통해 보여준다.

In [17]:
a = np.array([1,2,3])

In [22]:
b = a # view (원본 및 복사본 동시 변경)

In [23]:
b[1] = 4

In [24]:
b

array([1, 4, 3])

In [25]:
a

array([1, 4, 3])

In [26]:
# 딕셔너리 뷰 => key, value, item (key + value)

In [27]:
c = a.copy() # copy => numpy 에서는 기본이 deep copy 

In [29]:
# nan => float 형태 , 무한대 

In [30]:
# numpy 의 broadcasting 기법 

In [31]:
a = np.array( [20,30,40,50] )

In [39]:
a + 1 # broadcasting 모양이 달라도 연산을 가능하게 해주는 기법 

array([21, 31, 41, 51])

In [40]:
b = np.arange(4)

In [41]:
c = a - b

In [42]:
c

array([20, 29, 38, 47])

In [43]:
b

array([0, 1, 2, 3])

In [44]:
b**2 # square root 

array([0, 1, 4, 9])

In [45]:
np.full((2,2),4)

array([[4, 4],
       [4, 4]])

In [46]:
%timeit sum(range(10000))

173 µs ± 9.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [47]:
%timeit np.sum(np.arange(10000))

12.2 µs ± 61.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [48]:
# 제일 느림 
# temp = 0
# for i in range(10000):
#     temp += i

In [49]:
# SciPy 

In [50]:
sum(range(1001))/len(range(1001))

500.0

In [52]:
np.mean(np.arange(1001))

500.0

In [56]:
a = np.arange(10).reshape(2,-1)

In [64]:
a[1,2] 

7

In [77]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
... # Ellipsis

Ellipsis

In [67]:
a[...]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [72]:
# fancy indexing (copy 기법) 

In [73]:
# mask (true/false)

In [74]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [75]:
a[(a>2) & (a<8)]

array([3, 4, 5, 6, 7])

In [76]:
a[(a>2) | (a<8)]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [82]:
a[(a==9) | (a==3)] # 조건에 맞는 것만 가져온다. 

array([3, 9])

In [83]:
a[(a==9) | (a==3)] = 0 # view 

In [84]:
a

array([[0, 1, 2, 0, 4],
       [5, 6, 7, 8, 0]])

In [85]:
# higher order function => fromfunction 

In [86]:
def f(x,y):
    return 10*x+y

In [87]:
b = np.fromfunction(f,(5,4),dtype=int)

In [92]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [ ]:
# >>> def f(x,y):
# ...     return 10*x+y
# ...
# >>> b = np.fromfunction(f,(5,4),dtype=int)
# >>> b
# array([[ 0,  1,  2,  3],
#        [10, 11, 12, 13],
#        [20, 21, 22, 23],
#        [30, 31, 32, 33],
#        [40, 41, 42, 43]])
# >>> b[2,3]
# 23
# >>> b[0:5, 1]                       # each row in the second column of b
# array([ 1, 11, 21, 31, 41])
# >>> b[ : ,1]                        # equivalent to the previous example
# array([ 1, 11, 21, 31, 41])
# >>> b[1:3, : ]                      # each column in the second and third row of b
# array([[10, 11, 12, 13],
#        [20, 21, 22, 23]])

In [88]:
a = [1,2,3,4,5,6]

In [89]:
temp  = []
for i in a:
    temp.append(10**i)

In [91]:
list(map(lambda x: 10**x, a))

[10, 100, 1000, 10000, 100000, 1000000]

In [103]:
a = np.arange(10).reshape(2,5)

In [104]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a.ravel()[0] = 3 # view

In [106]:
a

array([[3, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [107]:
a.T # 행과 열 교체 

array([[3, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [101]:
a.flatten()[0] = 3 

In [102]:
a.flatten() # copy 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# indexing -> view, fancy indexing -> copy 