In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])

In [3]:
c = a[[0]] # fancy indexing => copy (indexing 중에 fancy indexing 만 copy)

In [4]:
c[0] = 0

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a[[0,1]][0]

array([1, 2, 3])

In [7]:
a[[0,1]]

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a[[0,1],[0]]

array([1, 4])

In [10]:
a[np.ix_([0,1],[0,2])] # 벡터 외적을 통해 0*0 = 0, 0*2 =0, 

array([[1, 3],
       [4, 6]])

In [11]:
a[::2]

array([[1, 2, 3]])

In [12]:
a[0][::2]

array([1, 3])

In [13]:
a[0:1][::2]

array([[1, 2, 3]])

In [14]:
a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a[:][0]

array([1, 2, 3])

In [17]:
a[[0,1]][:,[0,2]]

array([[1, 3],
       [4, 6]])

In [18]:
a[:,[0,2]]

array([[1, 3],
       [4, 6]])

In [21]:
import inspect # 소스 알아보기 

In [22]:
print(inspect.getsource(np.vsplit))

def vsplit(ary, indices_or_sections):
    """
    Split an array into multiple sub-arrays vertically (row-wise).

    Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
    to ``split`` with `axis=0` (default), the array is always split along the
    first axis regardless of the array dimension.

    See Also
    --------
    split : Split an array into multiple sub-arrays of equal size.

    Examples
    --------
    >>> x = np.arange(16.0).reshape(4, 4)
    >>> x
    array([[  0.,   1.,   2.,   3.],
           [  4.,   5.,   6.,   7.],
           [  8.,   9.,  10.,  11.],
           [ 12.,  13.,  14.,  15.]])
    >>> np.vsplit(x, 2)
    [array([[ 0.,  1.,  2.,  3.],
           [ 4.,  5.,  6.,  7.]]),
     array([[  8.,   9.,  10.,  11.],
           [ 12.,  13.,  14.,  15.]])]
    >>> np.vsplit(x, np.array([3, 6]))
    [array([[  0.,   1.,   2.,   3.],
           [  4.,   5.,   6.,   7.],
           [  8.,   9.,  10.,  11.]]),
     array([[ 12.,  13.,  14.,  15.]])

In [23]:
# customized data type

In [27]:
dt = np.dtype([('moon',np.int16),('sun','i4')])

In [29]:
a = np.array([[1,2,3],[4,5,6]],dtype=dt)

In [30]:
a['moon'] # dictionary 방식 

array([[1, 2, 3],
       [4, 5, 6]], dtype=int16)

In [31]:
a['sun']

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)