In [5]:
import numpy as np

In [33]:
a = np.array([1,2,3,0,5,6,7,8])

In [34]:
c = np.array([1,2,3,4,5,6,7,8])

In [35]:
c = c.reshape((4,2))

In [47]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
d = c.copy() # deep copy 

In [49]:
d[0][0] = 100

In [50]:
d[0,0] 

100

In [51]:
c # 원본 그대로 유지됨 numpy 기본 copy는 deep copy 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [52]:
d

array([[100,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8]])

In [53]:
e = d[:] # swallow copy <- python 기본 copy 는 swallow copy

In [54]:
e

array([[100,   2],
       [  3,   4],
       [  5,   6],
       [  7,   8]])

In [55]:
e[0,0] = 1090

In [56]:
d 

array([[1090,    2],
       [   3,    4],
       [   5,    6],
       [   7,    8]])

In [31]:
# 좀 더 우아한 방법 

In [42]:
a

array([1, 2, 3, 0, 5, 6, 7, 8])

In [43]:
f = np.asarray(a)

In [44]:
f

array([1, 2, 3, 0, 5, 6, 7, 8])

In [57]:
d

array([[1090,    2],
       [   3,    4],
       [   5,    6],
       [   7,    8]])

In [75]:
f = np.asarray(d, dtype=np.float) # 원본 배열과 복사할 배열의 데이터 타입이 동일하면 asarray 는 swallow copy

In [76]:
f

array([[0., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [77]:
f[0,0] = 100000000

In [78]:
d # asarray 는 원본 배열과 복사할 배열의 데이터타입이 같으면 swallow copy 이고 데이터타입이 다르면 deep copy 

array([[0, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [79]:
x = np.ones_like(d) # shape을 똑같이 맞추고 전부 1만 들어가는 ndarray를 생성  

In [80]:
x

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [81]:
# ndarray 만드는 방법 4가지 

In [85]:
# 1. 처음부터 만드는 것 np.array / np.ones / np.eyes ..., 
# 2. 원본 copy 하는 것 asarray, ones_like..,
# 3. numpy 파일 불러오는 것
# 4. random으로 만드는 것 