### Automation / Web / Data
#### 위 주제 중 data 를 다룰 것이며 Numpy를 배울 것이다.

### Numpy
#### 주로 숫자 관련 데이터 처리를 하게 된다. 
#### openCV를 이용하여 이미지 처리를 할 수 있고 이를 Numpy 포맷으로 처리 가능하며 반대로도 가능하다. 
#### Text는 Numpy로 하지 않는다. 

In [6]:
import numpy as np

In [7]:
#import array # python 지원 어레이 잘 안 씀 

In [8]:
# @ => 파이선 연산자 (numpy만 지원)

In [9]:
a = np.array([1,'1']) # order -> 데이터 저장 방식 => C or Fortran 방식 

In [11]:
a # 데이터 타입이 서로 같아야 하는데 다르게 했더니 자동으로 문자열로 바꿔줌 

array(['1', '1'], dtype='<U21')

In [12]:
a = np.array([1,2,3,4])

In [13]:
a

array([1, 2, 3, 4])

In [15]:
dir(a) # vector 계산 함수가 포함

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

In [16]:
a.sum()

10

In [17]:
a = np.array(range(10000000))

In [18]:
%timeit a.sum()

5.68 ms ± 78.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%timeit sum(range(10000000))

168 ms ± 130 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
type(a)

numpy.ndarray

In [26]:
b = np.ones((10,3)) # 10 rows / 3 columns 

In [27]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
b = np.zeros((2,3,4)) # 2 * 3 * 4 => 컬러 이미지 

In [33]:
b

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [36]:
c = np.zeros((3,3,3)) # 전부 0으로 초기화시켜라 

In [37]:
c

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
d = np.eye(4)

In [39]:
d

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
e = np.empty(5)

In [41]:
e

array([-2.31584178e+077, -2.68678729e+154,  3.45845952e-323,
        0.00000000e+000,  0.00000000e+000])

In [42]:
f = np.arange(1,11)

In [43]:
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
f[1]

2

In [45]:
g = np.array([[1,2,3],[4,5,6]])

In [46]:
g

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
g[0]

array([1, 2, 3])

In [49]:
g[0][1]

2

In [52]:
g.shape # 2 rows / 3 columns

(2, 3)

In [54]:
g.ndim # 몇 차원인가?

2

In [55]:
g.dtype

dtype('int64')

In [57]:
# int64 => 8 bytes 로 나눠야 함 

In [58]:
g.strides # 24 / 8 bytes (64 bit), 8 / 8 bytes (64 bit) = 3,1 등간격 * * * | * * * 

(24, 8)