### Numpy (2)

In [3]:
import numpy as np

In [33]:
a = np.array([1,2,3,4,5,6,7,8]) # array는 mutable 이다.

In [34]:
# data를 한 줄로 받고 reshape을 통해서 모양을 바꾼다. reshape 자체는 immutable 이며 할당을 해야 원본이 바뀐다. 

In [39]:
a = a.reshape((2,4)) # 만들고 나서 모양을 바꾼다. view <- 원본은 안 바뀌고 모양만 바꾼다. / 할당을 하면 원본이 바뀐다. 

In [38]:
a[0:2,1:3] # slicing 이 가능 

array([[2, 3],
       [6, 7]])

In [19]:
a

array([1, 2, 3, 6, 5, 6, 7, 8])

In [16]:
a.reshape((2,4))

array([[1, 2, 3, 6],
       [5, 6, 7, 8]])

In [8]:
b = [1,2,3]

In [9]:
b.append(4)

In [10]:
b

[1, 2, 3, 4]

In [21]:
c = [[1,2,3,4],[5,6,7,8]]

In [22]:
c[1,1]

TypeError: list indices must be integers or slices, not tuple