In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8])

In [3]:
b = a

In [4]:
b[3] = 0

In [5]:
a # mutable 이라서 바뀌었음 => a와 b 둘 다 바뀜 

array([1, 2, 3, 0, 5, 6, 7, 8])

In [10]:
c = a.copy() # a의 원본 그대로 유지하고 싶어할 때 

In [7]:
c

array([1, 2, 3, 0, 5, 6, 7, 8])

In [8]:
c[0] = 0

In [9]:
a

array([1, 2, 3, 0, 5, 6, 7, 8])