In [1]:
# Numpy 에서의 sequence 

In [2]:
# a[0][0][0] => a[0,0,0] 으로 쓸 수 있음 axis 는 열 

In [3]:
# 값을 3가지로 구할 수 있음 -> 전체 값, 각 행의 합의 값, axis를 통해 각 열의 합의 값

In [1]:
import numpy as np

In [2]:
a = np.arange(12)

In [3]:
a = a.reshape(4,3)

In [10]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
a.sum

<function ndarray.sum>

In [12]:
a.sum()

66

In [14]:
a.sum(axis=0) # 0 + 3 + 6 + 9 / 1 + 4 + 7 + 10 / 2 + 5 + 8 + 11

array([18, 22, 26])

In [15]:
a.sum(axis=1)

array([ 3, 12, 21, 30])